# Generated by Django 3.2.8 on 2021-12-05 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Highest_Level_of_Education', models.CharField(choices=[('hs', 'High School'), ('col', 'College/Diploma'), ('deg', 'Undergraduate Degree'), ('ma', 'Masters Degree'), ('phd', 'Doctoral Degree'), ('Pro', 'Professional Degree')], max_length=3)),
                ('CourseField_of_Study', models.CharField(max_length=50)),
                ('CV', models.FileField(help_text='Drag and drop or click to upload your cv', upload_to='', verbose_name='C.V')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(choices=[('Null', '*Select'), ('diploma', 'College/diploma'), ('undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('Phd', 'Phd')], max_length=20)),
                ('type_of_paper', models.CharField(choices=[('Null', '*Select'), ('Essay', 'Essay (Any Type)'), ('Abstract', 'Abstract'), ('admission Essay', 'admission Essa'), ('Annotated Bibliography', 'Annotated Bibliography'), ('Argumentativ Essay', 'Argumentativ Essay'), ('Article (Any Type)', 'Article (Any Type)'), ('Article Review', 'Article Review'), ('Article Summary', 'Article Summary'), ('Assessment', 'Assessment'), ('Book report', 'Book report'), ('Book review', 'Book review'), ('Book/Movie Review', 'Book/Movie Review'), ('Breafing paper', 'Breafing paper'), ('Business Plan', 'Business Plan'), ('Capstone project', 'Capstone project'), ('Cases Study', 'Cases Study'), ('Content (Any Type)', 'Content (Any Type)'), ('Coursework', 'Coursework'), ('Cover letter', 'Cover letter'), ('Creative writing', 'Cover letter'), ('Critical thinking', 'Critical thinking'), ('data analysis', 'data analysis'), ('Design paper', 'Design paper'), ('Dissertation', 'Dissertation'), ('Editing/Proofreading', 'Editing/Proofreading'), ('Essay', 'Essay'), ('Executive Summary', 'Executive Summary'), ('Finance Excel Analysis', 'Finance Excel Analysis'), ('Financial Analysis', 'Financial Analysis'), ('Financial Statments', 'Financial Statments'), ('Journal Article', 'Journal Article'), ('Journal Entry', 'Journal Entry'), ('Lab report', 'Lab report'), ('Literature Review', 'Literature Review'), ('Marketing Plan', 'Marketing Plan'), ('Math Problem', 'Math Problem'), ('Mind concept-map', 'Mind concept-map'), ('Movie review', 'Movie review'), ('Multiple choices', 'Multiple choices'), ('Online Assignment', 'Online Assignment'), ('other (Not listed)', 'other (Not listed)'), ('PDF poster', 'PDF poster'), ('PESTLE Analysis', 'PESTLE Analysis'), ('Phys/Econ/Fin/Stat Problems', 'Phys/Econ/Fin/Stat Problems'), ('Presentation', 'Presentation'), ('Psychology Report', 'Psychology Report'), ('Q&A', 'Q&A'), ('Reaction Paper', 'Reaction Paper'), ('Report', 'Report'), ('Research Design/Methodology', 'Research Design/Methodology'), ('Research Paper', 'Research Paper'), ('Research proposal', 'Research proposal'), ('Research Summary', 'Research Summary'), ('Resume/CV', 'Resume/CV'), ('Rewriting', 'Rewriting'), ('Scholarship Essay', 'Scholarship Essay'), ('Short Answers', 'Short Answers'), ('Speech', 'Speech'), ('Speech Work', 'Speech Work'), ('Statstic Project', 'Statstic Project'), ('SWOT Analysis', 'SWOT Analysis'), ('Term Paper', 'Term Paper'), ('Thesis', 'Thesis'), ('Thesis/Dissertation - Discussion', 'Thesis/Dissertation - Discussion'), ('Thesis/Dissertation - Abstract', 'Thesis/Dissertation - Abstract'), ('Thesis/Dissertation - Conclusion', 'Thesis/Dissertation - Conclusion'), ('Thesis/Dissertation - Introduction', 'Thesis/Dissertation - Introduction'), ('Thesis/Dissertation - Literature Review', 'Thesis/Dissertation - Literature Review'), ('Thesis/Dissertation - Methodology', 'Thesis/Dissertation - Methodology'), ('Thesis/Dissertation - Outline/Form', 'Thesis/Dissertation - Outline/Form'), ('Thesis/Dissertation - Results', 'Thesis/Dissertation - Results'), ('Thesis/Dissertation Proposal', 'Thesis/Dissertation Proposal')], max_length=50)),
                ('subject_Area', models.CharField(choices=[('Null', '*Select Subject'), ('Accounting', 'Accounting'), ('Aeronautics', 'Aeronautics'), ('Anthropology', 'Anthropology'), ('Archeology', 'Archeology'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Astronomy', 'Astronomy'), ('Auditing', 'Auditing'), ('Aviation', 'Aviation'), ('Bio-Medical Sciences', 'Bio-Medical Sciences'), ('Biochemistry', 'Biochemistry'), ('Biolog', 'Biology'), ('Building & Construction', 'Building & Construction'), ('Business', 'Business'), ('Chemistry', 'Chemistry'), ('Childcare', 'Childcare'), ('Communication and Media', 'Communication and Media'), ('Company Anlysis', 'Company Anlysis'), ('Computers', 'Computers'), ('Counseling', 'Counseling'), ('Criminology', 'Criminology'), ('Economics', 'Economics'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('English', 'English'), ('Environmental-Studies', 'Environmental-Studies'), ('Ethics', 'Ethics'), ('Ethnic-Studies', 'Ethnic-Studies'), ('finance', 'finance'), ('Food-Nutrition', 'Food-Nutrition'), ('Geography', 'Geography'), ('Geology', 'Geology'), ('Healthcare', 'Healthcare'), ('History', 'History'), ('Internet', 'Internet'), ('Investment', 'Investment'), ('IT Management', 'IT Management'), ('Law', 'Law'), ('Legal Issues', 'Legal Issues'), ('Linguistics', 'Linguistics'), ('Literature', 'Literature'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Medicine', 'Medicine'), ('Military Studies', 'Military Studies'), ('Music', 'Music'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Other(Not Listed)', 'Other(Not Listed)'), ('Pedagogy', 'Pedagogy'), ('Pharmacology', 'Pharmacology'), ('Philosophy', 'Philosophy'), ('Physical-Education', 'Physical-Education'), ('Physics', 'Physics'), ('Physical Problems', 'Physical Problems'), ('Political Science', 'Political Science'), ('Politics', 'Politics'), ('Procurement', 'Procurement'), ('Psychology', 'Psychology'), ('Quantity Survey', 'Quantity Survey'), ('Religion', 'Religion'), ('Sociology', 'Sociology'), ('Sport', 'Sport'), ('Statistics', 'Statistics'), ('Taxation Theory, Practice & Law', 'Taxation Theory, Practice & Law'), ("Teacher's Career", "Teacher's Career"), ('Tourism', 'Tourism'), ('Trade', 'Trade')], max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('paper_instructions', models.TextField()),
                ('Additional_materials', models.FileField(help_text='Please upload any addtional files here', upload_to='')),
                ('paper_format', models.CharField(choices=[('Null', '*Select'), ('APA', 'APA'), ('MLA', 'MLA'), ('Harvard', 'Harvard'), ('Other', 'Other'), ('OSCOLA', 'OSCOLA'), ('AGLC', 'AGLC'), ('Chicago', 'Chicago'), ('Oxford', 'Oxford')], max_length=50)),
                ('number_of_pages', models.IntegerField()),
                ('spacing', models.CharField(choices=[('Null', '*Select'), ('single', 'Single spaced'), ('double', 'Double spaced')], max_length=50)),
                ('currency', models.CharField(default='$', editable=False, max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
