# Generated by Django 3.2.8 on 2022-02-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_alter_bid_project'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectOrder',
        ),
    ]
