# Generated by Django 3.2.8 on 2021-12-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211210_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectorder',
            name='slug',
            field=models.SlugField(default='test project'),
            preserve_default=False,
        ),
    ]
