# Generated by Django 3.2.8 on 2021-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211211_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectorder',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
