# Generated by Django 3.2.8 on 2022-01-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_projectorder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectorder',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='academic_level',
            field=models.CharField(choices=[('diploma', 'College/diploma'), ('undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('Phd', 'Phd')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='paper_format',
            field=models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Harvard', 'Harvard'), ('Other', 'Other'), ('OSCOLA', 'OSCOLA'), ('AGLC', 'AGLC'), ('Chicago', 'Chicago'), ('Oxford', 'Oxford')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='spacing',
            field=models.CharField(choices=[('single', 'Single spaced'), ('double', 'Double spaced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='subject_area',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Aeronautics', 'Aeronautics'), ('Anthropology', 'Anthropology'), ('Archeology', 'Archeology'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Astronomy', 'Astronomy'), ('Auditing', 'Auditing'), ('Aviation', 'Aviation'), ('Bio-Medical Sciences', 'Bio-Medical Sciences'), ('Biochemistry', 'Biochemistry'), ('Biolog', 'Biology'), ('Building & Construction', 'Building & Construction'), ('Business', 'Business'), ('Chemistry', 'Chemistry'), ('Childcare', 'Childcare'), ('Communication and Media', 'Communication and Media'), ('Company Anlysis', 'Company Analysis'), ('Computers', 'Computers'), ('Counseling', 'Counseling'), ('Criminology', 'Criminology'), ('Economics', 'Economics'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('English', 'English'), ('Environmental-Studies', 'Environmental-Studies'), ('Ethics', 'Ethics'), ('Ethnic-Studies', 'Ethnic-Studies'), ('finance', 'finance'), ('Food-Nutrition', 'Food-Nutrition'), ('Geography', 'Geography'), ('Geology', 'Geology'), ('Healthcare', 'Healthcare'), ('History', 'History'), ('Internet', 'Internet'), ('Investment', 'Investment'), ('IT Management', 'IT Management'), ('Law', 'Law'), ('Legal Issues', 'Legal Issues'), ('Linguistics', 'Linguistics'), ('Literature', 'Literature'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Medicine', 'Medicine'), ('Military Studies', 'Military Studies'), ('Music', 'Music'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Other(Not Listed)', 'Other(Not Listed)'), ('Pedagogy', 'Pedagogy'), ('Pharmacology', 'Pharmacology'), ('Philosophy', 'Philosophy'), ('Physical-Education', 'Physical-Education'), ('Physics', 'Physics'), ('Physical Problems', 'Physical Problems'), ('Political Science', 'Political Science'), ('Politics', 'Politics'), ('Procurement', 'Procurement'), ('Psychology', 'Psychology'), ('Quantity Survey', 'Quantity Survey'), ('Religion', 'Religion'), ('Sociology', 'Sociology'), ('Sport', 'Sport'), ('Statistics', 'Statistics'), ('Taxation Theory, Practice & Law', 'Taxation Theory, Practice & Law'), ("Teacher's Career", "Teacher's Career"), ('Tourism', 'Tourism'), ('Trade', 'Trade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='type_of_paper',
            field=models.CharField(choices=[('Essay', 'Essay (Any Type)'), ('Abstract', 'Abstract'), ('admission Essay', 'Admission Essay'), ('Annotated Bibliography', 'Annotated Bibliography'), ('Argumentativ Essay', 'Argumentative Essay'), ('Article (Any Type)', 'Article (Any Type)'), ('Article Review', 'Article Review'), ('Article Summary', 'Article Summary'), ('Assessment', 'Assessment'), ('Book report', 'Book Report'), ('Book review', 'Book Review'), ('Book/Movie Review', 'Book/Movie Review'), ('Breafing paper', 'Breafing Paper'), ('Business Plan', 'Business Plan'), ('Capstone project', 'Capstone Project'), ('Cases Study', 'Cases Study'), ('Content (Any Type)', 'Content (Any Type)'), ('Coursework', 'Coursework'), ('Cover letter', 'Cover Letter'), ('Creative writing', 'Creative Writing'), ('Critical thinking', 'Critical Thinking'), ('data analysis', 'Data Analysis'), ('Design paper', 'Design Paper'), ('Dissertation', 'Dissertation'), ('Editing/Proofreading', 'Editing/Proofreading'), ('Essay', 'Essay'), ('Executive Summary', 'Executive Summary'), ('Finance Excel Analysis', 'Finance Excel Analysis'), ('Financial Analysis', 'Financial Analysis'), ('Financial Statments', 'Financial Statments'), ('Journal Article', 'Journal Article'), ('Journal Entry', 'Journal Entry'), ('Lab report', 'Lab Report'), ('Literature Review', 'Literature Review'), ('Marketing Plan', 'Marketing Plan'), ('Math Problem', 'Math Problem'), ('Mind concept-map', 'Mind Concept-Map'), ('Movie review', 'Movie Review'), ('Multiple choices', 'Multiple Choices'), ('Online Assignment', 'Online Assignment'), ('other (Not listed)', 'other (Not listed)'), ('PDF poster', 'PDF Poster'), ('PESTLE Analysis', 'PESTLE Analysis'), ('Phys/Econ/Fin/Stat Problems', 'Phys/Econ/Fin/Stat Problems'), ('Presentation', 'Presentation'), ('Psychology Report', 'Psychology Report'), ('Q&A', 'Q&A'), ('Reaction Paper', 'Reaction Paper'), ('Report', 'Report'), ('Research Design/Methodology', 'Research Design/Methodology'), ('Research Paper', 'Research Paper'), ('Research proposal', 'Research Proposal'), ('Research Summary', 'Research Summary'), ('Resume/CV', 'Resume/CV'), ('Rewriting', 'Rewriting'), ('Scholarship Essay', 'Scholarship Essay'), ('Short Answers', 'Short Answers'), ('Speech', 'Speech'), ('Speech Work', 'Speech Work'), ('Statstic Project', 'Statstic Project'), ('SWOT Analysis', 'SWOT Analysis'), ('Term Paper', 'Term Paper'), ('Thesis', 'Thesis'), ('Thesis/Dissertation - Discussion', 'Thesis/Dissertation - Discussion'), ('Thesis/Dissertation - Abstract', 'Thesis/Dissertation - Abstract'), ('Thesis/Dissertation - Conclusion', 'Thesis/Dissertation - Conclusion'), ('Thesis/Dissertation - Introduction', 'Thesis/Dissertation - Introduction'), ('Thesis/Dissertation - Literature Review', 'Thesis/Dissertation - Literature Review'), ('Thesis/Dissertation - Methodology', 'Thesis/Dissertation - Methodology'), ('Thesis/Dissertation - Outline/Form', 'Thesis/Dissertation - Outline/Form'), ('Thesis/Dissertation - Results', 'Thesis/Dissertation - Results'), ('Thesis/Dissertation Proposal', 'Thesis/Dissertation Proposal')], max_length=50),
        ),
    ]
