# Generated by Django 3.2.8 on 2022-01-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220104_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectorder',
            name='price',
            field=models.FloatField(default=4),
        ),
    ]
