# Generated by Django 3.2.8 on 2022-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_projectorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='assign',
            field=models.BooleanField(default=False),
        ),
    ]
