# Generated by Django 3.2.8 on 2022-01-05 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_bid_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectorder',
            name='is_active',
        ),
        migrations.AddField(
            model_name='projectorder',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='type_of_paper',
            field=models.CharField(choices=[('Essay', 'Essay (Any Type)'), ('Abstract', 'Abstract'), ('admission Essay', 'Admission Essay'), ('Annotated Bibliography', 'Annotated Bibliography'), ('Argumentative Essay', 'Argumentative Essay'), ('Article (Any Type)', 'Article (Any Type)'), ('Article Review', 'Article Review'), ('Article Summary', 'Article Summary'), ('Assessment', 'Assessment'), ('Book report', 'Book Report'), ('Book review', 'Book Review'), ('Book/Movie Review', 'Book/Movie Review'), ('Breafing paper', 'Breafing Paper'), ('Business Plan', 'Business Plan'), ('Capstone project', 'Capstone Project'), ('Cases Study', 'Cases Study'), ('Content (Any Type)', 'Content (Any Type)'), ('Coursework', 'Coursework'), ('Cover letter', 'Cover Letter'), ('Creative writing', 'Creative Writing'), ('Critical thinking', 'Critical Thinking'), ('data analysis', 'Data Analysis'), ('Design paper', 'Design Paper'), ('Dissertation', 'Dissertation'), ('Editing/Proofreading', 'Editing/Proofreading'), ('Essay', 'Essay'), ('Executive Summary', 'Executive Summary'), ('Finance Excel Analysis', 'Finance Excel Analysis'), ('Financial Analysis', 'Financial Analysis'), ('Financial Statments', 'Financial Statments'), ('Journal Article', 'Journal Article'), ('Journal Entry', 'Journal Entry'), ('Lab report', 'Lab Report'), ('Literature Review', 'Literature Review'), ('Marketing Plan', 'Marketing Plan'), ('Math Problem', 'Math Problem'), ('Mind concept-map', 'Mind Concept-Map'), ('Movie review', 'Movie Review'), ('Multiple choices', 'Multiple Choices'), ('Online Assignment', 'Online Assignment'), ('other (Not listed)', 'other (Not listed)'), ('PDF poster', 'PDF Poster'), ('PESTLE Analysis', 'PESTLE Analysis'), ('Phys/Econ/Fin/Stat Problems', 'Phys/Econ/Fin/Stat Problems'), ('Presentation', 'Presentation'), ('Psychology Report', 'Psychology Report'), ('Q&A', 'Q&A'), ('Reaction Paper', 'Reaction Paper'), ('Report', 'Report'), ('Research Design/Methodology', 'Research Design/Methodology'), ('Research Paper', 'Research Paper'), ('Research proposal', 'Research Proposal'), ('Research Summary', 'Research Summary'), ('Resume/CV', 'Resume/CV'), ('Rewriting', 'Rewriting'), ('Scholarship Essay', 'Scholarship Essay'), ('Short Answers', 'Short Answers'), ('Speech', 'Speech'), ('Speech Work', 'Speech Work'), ('Statstic Project', 'Statstic Project'), ('SWOT Analysis', 'SWOT Analysis'), ('Term Paper', 'Term Paper'), ('Thesis', 'Thesis'), ('Thesis/Dissertation - Discussion', 'Thesis/Dissertation - Discussion'), ('Thesis/Dissertation - Abstract', 'Thesis/Dissertation - Abstract'), ('Thesis/Dissertation - Conclusion', 'Thesis/Dissertation - Conclusion'), ('Thesis/Dissertation - Introduction', 'Thesis/Dissertation - Introduction'), ('Thesis/Dissertation - Literature Review', 'Thesis/Dissertation - Literature Review'), ('Thesis/Dissertation - Methodology', 'Thesis/Dissertation - Methodology'), ('Thesis/Dissertation - Outline/Form', 'Thesis/Dissertation - Outline/Form'), ('Thesis/Dissertation - Results', 'Thesis/Dissertation - Results'), ('Thesis/Dissertation Proposal', 'Thesis/Dissertation Proposal')], max_length=50),
        ),
    ]
