# Generated by Django 3.2.8 on 2022-02-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220123_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectorder',
            name='price',
            field=models.FloatField(default=0.0, help_text='This field is auto-generated hence cannot be changed'),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='subject_area',
            field=models.CharField(choices=[('Accounting', 'Accounting'), ('Aeronautics', 'Aeronautics'), ('Anthropology', 'Anthropology'), ('Archeology', 'Archeology'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Astronomy', 'Astronomy'), ('Auditing', 'Auditing'), ('Aviation', 'Aviation'), ('Bio-Medical Sciences', 'Bio-Medical Sciences'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Building & Construction', 'Building & Construction'), ('Business', 'Business'), ('Chemistry', 'Chemistry'), ('Childcare', 'Childcare'), ('Communication and Media', 'Communication and Media'), ('Company Analysis', 'Company Analysis'), ('Computers', 'Computers'), ('Counseling', 'Counseling'), ('Criminology', 'Criminology'), ('Economics', 'Economics'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('English', 'English'), ('Environmental-Studies', 'Environmental-Studies'), ('Ethics', 'Ethics'), ('Ethnic-Studies', 'Ethnic-Studies'), ('finance', 'finance'), ('Food-Nutrition', 'Food-Nutrition'), ('Geography', 'Geography'), ('Geology', 'Geology'), ('Healthcare', 'Healthcare'), ('History', 'History'), ('Internet', 'Internet'), ('Investment', 'Investment'), ('IT Management', 'IT Management'), ('Law', 'Law'), ('Legal Issues', 'Legal Issues'), ('Linguistics', 'Linguistics'), ('Literature', 'Literature'), ('Logistics', 'Logistics'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Medicine', 'Medicine'), ('Military Studies', 'Military Studies'), ('Music', 'Music'), ('Nursing', 'Nursing'), ('Nutrition', 'Nutrition'), ('Other(Not Listed)', 'Other(Not Listed)'), ('Pedagogy', 'Pedagogy'), ('Pharmacology', 'Pharmacology'), ('Philosophy', 'Philosophy'), ('Physical-Education', 'Physical-Education'), ('Physics', 'Physics'), ('Physical Problems', 'Physical Problems'), ('Political Science', 'Political Science'), ('Politics', 'Politics'), ('Procurement', 'Procurement'), ('Psychology', 'Psychology'), ('Quantity Survey', 'Quantity Survey'), ('Religion', 'Religion'), ('Sociology', 'Sociology'), ('Sport', 'Sport'), ('Statistics', 'Statistics'), ('Taxation Theory, Practice & Law', 'Taxation Theory, Practice & Law'), ("Teacher's Career", "Teacher's Career"), ('Tourism', 'Tourism'), ('Trade', 'Trade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectorder',
            name='update_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
