# Generated by Django 3.2.8 on 2022-02-07 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('assign', models.BooleanField(default=False)),
                ('made_by', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='users.projectorder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_task', models.FileField(help_text='Upload the completed test task here', upload_to='test_tasks')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompleteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_task', models.FileField(help_text='upload the finished task here', upload_to='finals')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.bid')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=128)),
                ('Last_Name', models.CharField(max_length=128)),
                ('Highest_Level_of_Education', models.CharField(choices=[('hs', 'High School'), ('col', 'College/Diploma'), ('deg', 'Undergraduate Degree'), ('ma', 'Masters Degree'), ('phd', 'Doctoral Degree'), ('Pro', 'Professional Degree')], max_length=3)),
                ('CourseField_of_Study', models.CharField(max_length=250, verbose_name='Course/Field of Study')),
                ('CV', models.FileField(help_text='Drag and drop or click to upload your cv', upload_to='CVs', verbose_name='C.V')),
                ('Identification', models.ImageField(default='profile_pics/default.jpg', help_text='scan of your government issued ID', upload_to='gov_id')),
                ('photo_id', models.ImageField(default='profile_pics/default.jpg', help_text='photo of you holding your ID', upload_to='photo_id')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
