# Generated by Django 3.2.8 on 2022-02-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('writer', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='project',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='client.projectorder'),
        ),
    ]
